name: string_formatter_kit
description: This package contains tools to reading strings into maps using regex models and vice versa
version: 0.0.1+dev0
homepage: https://moti.monster
repository: https://github.com/FMotalleb/string_formatter_kit

environment:
  sdk: ">=2.18.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
